development:
  address: "smtp.gmail.com"
  port: "587"
  domain: "aron.com"
  authentication: "plain"
  user_name: "aron791227@gmail.com"
  password: "f127802022"
  enable_starttls_auto: true
production:
  address: "smtp.mailgun.org"
  port: "587"
  domain: "ihower.com"
  authentication: "plain"
  user_name: "postmaster@ihower.tw"
  password: "1234567890"
  enable_starttls_auto: true