# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db9f2f0278e3e97c78d8de1184a1fc21a8862c1eb99a8359953e81f4357d7bf11f0e1462fde64b28efe57e54c956228c0ab3f4593d4883ab4d881c1ba11b7293

test:
  secret_key_base: 8d6277cff72185488a24645fdce976548ecd5b5e3eadf73c146c247db582c057864ddbcd3b8cc1869f16af0e0683cb21b4bc4ca3b7eafedc4aa7ad375b67dbff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 8d6277cff72185488a24645fdce976548ecd5b5e3eadf73c146c247db582c057864ddbcd3b8cc1869f16af0e0683cb21b4bc4ca3b7eafedc4aa7ad375b67dbff %>
